spring:
    profiles:
        active: h2, docs
    output:
        ansi:
            enabled: DETECT
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
                show_sql: true
                use_sql_comments: true
        show-sql: true

logging:
    level:
        com:
            xinhnguyen: DEBUG
        org:
            hibernate: ERROR
            springframework:
                web: ERROR
    path: logs
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
        file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

info:
    app:
        name: Spring Sample Application
        description: This is my first spring boot application
        version: 1.0.0

user:
    firstname: nguyen
    lastname: xinh
---
spring:
    profiles: prod
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/db?useSSL=false
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: validate
---
spring:
    profiles: h2
    datasource:
        url: jdbc:h2:./data/spring-monolithic;MODE=MYSQL # jdbc:h2:mem:test_mem
    jpa:
        hibernate:
            ddl-auto: create-drop
    h2:
        console:
            enabled: true
---
spring:
    profiles: dev
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/spring-monolithic?createDatabaseIfNotExist=true
        username: root
        password: 123
    jpa:
        hibernate:
            ddl-auto: create-drop